### ISSUE TITLE
NullReferenceException in NetworkManager

### ISSUE THREAD

**Issue by SPoelloth** [SPoelloth/SWP16#29]
Bei einem Klick auf "Computer hinzufügen" gibt es im NetworkManager eine NullReferenceException.
Der Algorithmus um einen eindeutigen Namen zu erstellen hat einen Fehler. 
Mein Vorschlag:
Den Typ der Node + eine aufsteigende Zahl, dazu die Prüfung ob der Name eindeutig ist, wenn nicht, dann die Zahl um 1 erhöhen.
-> "Computer 1" "Computer 2" usw.

**Comment by dim5RT5k** [comment]
Habe den Bug gefixed.
Habe das Namensschema vorerst so belassen (also "A", "B"). Glaube so war das auch bei den Aufgaben in den Rechnernetzen.
Wenn wir aber ein anderes Schema verwenden wollen, kann ich das dann später ändern.
