### ISSUE TITLE
Noch einige Methoden im NetworkManager o.ä. benötigt

### ISSUE THREAD

**Issue by mclmw** [SPoelloth/SWP16#32]
Ich bräuchte noch ein paar Methoden, die mir neue Interfaces, Routen und ggf. Layers(wobei da die Implementierung noch nicht klar ist) liefert.
Sowas wie: NetworkManager.GetNewInterface() etc.
Siehe dazu auch PropertyController.cs #region Event Handling

Wusste nicht genau wer dafür zuständig ist, ggf. ändern bitte

Sobald NetworkManager.Instance.GetHardwarenodeByName(elementName) auch mal wirklich was zurückliefert sollten dann grundlegende Einstellungen möglich/testbar sein.

**Comment by dim5RT5k** [comment]
Hi,

die Methoden sind nun im NetworkManager drin.
(Schreibe das noch extra als E-Mail, weil heute einige Leute
gemeint haben, dass sie nicht alle Nofifications von GitHub kriegen).

Allerdings werden noch keine Layers zurückgeliefert. Die sind noch in 
der Workstation als "protected" deklariert. Falls du die brauchen 
solltest, dann sag am Besten wie die zugehörigen Methoden aussehen sollen..

Gruß

Dimitrij

Am 10.06.2016 um 23:00 schrieb mclmw:
