### ISSUE TITLE
Workstation/Router bekommen derzeit noch keinen Gateway gesetzt

### ISSUE THREAD

**Issue by mclmw** [SPoelloth/SWP16#38]
In beidem sollte standardmäßig beim Erstellen ein Gateway miterstellt werden.

Zudem sollte im NetworkManager in der Methode public void GatewayChanged(string WorkstationName, IPAddress Gateway, bool HasInternetAccess) etwas mit dem HasInternetAccessFlag und dem InterfaceNamen passieren (dem Gateway zugewiesen werden).

**Comment by JPsychotic** [comment]
Ich werde das demnächst implementieren :)
