### ISSUE TITLE
Simulation: IPAddress ist nun string

### ISSUE THREAD

**Issue by JPsychotic** [SPoelloth/SWP16#44]
Die Simulation hat nun keine IPAdressen Source & Destination mehr, sondern Rechnernamen.
Bitte zeige dann im Simulationstab diese Namen an! Ggf. musst du hald deinen Code bisschen abändern!

**Comment by JPsychotic** [comment]
Der Code builed, weil du wahrscheinlich bei den IPAddressen ein ToString() verwendest, was jetzt weg kann :)

**Comment by ladymagnetic** [comment]
jup, hab toString() verwendet. Aber so wars wenigstens nicht schlimm, dass ichs nicht gleich gesehen habe... Commit folgt nach nem kleinen Test
