### ISSUE TITLE
Icons für alle Buttons finden

### ISSUE THREAD

**Issue by SPoelloth** [SPoelloth/SWP16#48]

**Comment by Resi12** [comment]
wie groß sollen die Icons sein?

**Comment by SPoelloth** [comment]
Ich würd mal sagen mindestens 50x50.
runterskalieren geht immer, rauf nicht.

**Comment by Resi12** [comment]
ok ich schau mal was ich find

**Comment by Resi12** [comment]
für Workstation, Router, Switch auch Icons oder die Bilder wo auch auf der Designfläche sind?

**Comment by SPoelloth** [comment]
Mir wurscht.

**Comment by Resi12** [comment]
Also ich würde die Bilder, wo du für die Designfläche nimmst, nehmen. Die anderen Icons hab ich mal in Implementierung mit eingefügt.

**Comment by SPoelloth** [comment]
Lass morgen die Icons auch beim Teammeeting diskutieren. Da würd ich auch die Darstellung der Netzwerkelemente diskutieren. Ob da jemand wegen den Farben bessere Vorschläge hat.

**Comment by Resi12** [comment]
Ich bin morgen leider nicht im Meeting, aber ihr könnt es diskutieren und wenn die icons nicht passen such ich noch andere

**Comment by Mirjam1** [comment]
Hallo!

Sorry, war länger nicht online. Soll ich noch Icons suchen oder hat sich das erledigt? 

```
Resi12 <notifications@github.com> schrieb am 20:41 Sonntag, 19.Juni 2016:
```

 Ich bin morgen leider nicht im Meeting, aber ihr könnt es diskutieren und wenn die icons nicht passen such ich noch andere—

**Comment by Resi12** [comment]
Nein auf github sind bereits ein paar icons ;)

**Comment by mclmw** [comment]
Icons hab ich mal in die View verschoben, es fehlen noch Icons für Workstation, Router, Switch

**Comment by SPoelloth** [comment]
Workstation, Router, Switch Icons hinzugefügt.
Es fehlen noch Screenshot und Broadcast Icons.

**Comment by Resi12** [comment]
Bitte ins Projekt die letzten beiden Icons einfügen
