### ISSUE TITLE
Linux: PropertyControl, Probleme beim Scrollen

### ISSUE THREAD

**Issue by SPoelloth** [SPoelloth/SWP16#49]
Auf Linux: Wenn ein Scrollbalken angezeigt wird auf die "freie" Fläche klicken, wo kein Balken ist, um nach unten zu scrollen.
Resultat: Bildfehler.

**Comment by mclmw** [comment]
Es gibt immer noch ein Problem mit dem Scrollbar der PropertyControl. Wenn man per Klick in die Scrollbar (nicht auf den Scrollbalken) scrollt, kann es vorkommen, dass das Control "hängen bleibt", es wird schlicht nicht richtig gezeichnet, weiteres Scrollen sorgt aber dafür dass es wieder passt. Normales Scrollen funktioniert soweit auch. Ich halte das für ein äusserst spezifisches, nicht die Funktionalität einschränkendes Problem, das ausschließlich unter Linux auftritt und deswegen mit vernünftigem Zeitaufwand (ich habe bereits mehrere Stunden in dieses Problem investiert) nicht kriegsentscheidend für unsere Applikation ist. Falls jemand sich damit noch befassen möchte, weil er noch Stunden braucht, so möge er dies tun, aber ich habe aufgegeben.
