### ISSUE TITLE
History leeren/Eintrag aus Simulationshistory löschen

### ISSUE THREAD

**Issue by SPoelloth** [SPoelloth/SWP16#55]
Einträge aus History müssen entfernbar sein bzw. die History muss löschbar sein.
Wenn man Bspw. Simulationen ausführt und dann ein anderes Projekt öffnet hat man noch die alten Simulationen drin.

**Comment by SPoelloth** [comment]
Bitte richtiger Person zuweisen.

**Comment by Resi12** [comment]
ich glaub das müsste im SimulationManager gemacht werden, bin mir aber nicht sicher

**Comment by Mirjam1** [comment]
Ja, Jeremy ist unser Simulationsexperte. ;)
