### ISSUE TITLE
Simulation geht nicht über einen Switch

### ISSUE THREAD

**Issue by SPoelloth** [SPoelloth/SWP16#56]
Simulation geht nicht wenn ein Switch zwischen den Rechnern hängt. Siehe Testprojekt:

[Simulation_ueber_Switch.zip](https://github.com/SPoelloth/SWP16/files/322460/Simulation_ueber_Switch.zip)

**Comment by SPoelloth** [comment]
Ich weiß nicht, muss ich da irgendwas zusätzlich einstellen mit den Routen?
Wenn ich (im RL) 2 Rechner zusammensteck und manuell IP Adressen festleg dann kann ich die gegenseitig anpingen weil die ja im gleichen Subnetz hängen.
Achja wie immer Assignees richtig festlegen, keine Ahnung wer was macht.

**Comment by denis631** [comment]
Soweit ich weiß, muss Du die Routen manuell einstellen. @ReVoluti0n weiß genauer, was gemacht werden soll
