### ISSUE TITLE
Layerstackvisualisierung testen

### ISSUE THREAD

**Issue by Resi12** [SPoelloth/SWP16#69]
MAX: Hey, also ich hab da jetzt mal auf die Schnelle was zusammengeschustert. Es scheint grundsätzlich auch zu funktionieren aber ich hab leider nicht mehr die Zeit heute um das zu testen. Prinzipielle Funktionsweise ist Hop auswählen, auf den HopVisualisierungstab wechseln und anschauen. Bei Bugs etc. auf mich stellen aber ich kann nicht versprechen dass ich die bis morgen gefixt bekomme. Sollte aus irgendwas ein Crash resultieren würde ich vorschlagen dem Ding die Funktionalität abzuklemmen (hopcontrol.HopSelected Event unsubscriben, im InfoController).

Achja: Habe nur Theresa assigned weil ich nicht weiß wer hier sonst noch momentan für Test zuständig ist, sorry.

**Comment by mclmw** [comment]
Hey, also ich hab da jetzt mal auf die Schnelle was zusammengeschustert. Es scheint grundsätzlich auch zu funktionieren aber ich hab leider nicht mehr die Zeit heute um das zu testen. Prinzipielle Funktionsweise ist Hop auswählen, auf den HopVisualisierungstab wechseln und anschauen. Bei Bugs etc. auf mich stellen aber ich kann nicht versprechen dass ich die bis morgen gefixt bekomme. Sollte aus irgendwas ein Crash resultieren würde ich vorschlagen dem Ding die Funktionalität abzuklemmen (hopcontrol.HopSelected Event unsubscriben, im InfoController).

Achja: Habe nur Theresa assigned weil ich nicht weiß wer hier sonst noch momentan für Test zuständig ist, sorry.

**Comment by Resi12** [comment]
Also das Visualisieren funktioniert soweit schon, nur wenn es keine Route gibt dann ist alles grün.
