### ISSUE TITLE
NetworkManager ToDo + Crash

### ISSUE THREAD

**Issue by ladymagnetic** [SPoelloth/SWP16#76]
// TODO: Do something with HasInternetAccess and InterfaceName in GatewayChanged()

Crash:
Programm starten, Workstation hinzufügen.
Im PropertyControl bei Standardgateway Schnittstelle auswählen.
=> InvalidOperationException in Methode GatewayChanged()

**Comment by JPsychotic** [comment]
Das ToDo kann normalerweise, das habe ich nur aus Versehen drin gelassen, der Crash passiert bei mir aber nicht...

**Comment by SPoelloth** [comment]
Crash is schon fixed? -> Max fragen

**Comment by ladymagnetic** [comment]
Crash passiert bei mir auch nicht mehr. Vielleicht tatsächlich schon anderweitig gefixt.

**Comment by mclmw** [comment]
Hab ich glaub ich schon gefixt, hatte das Issue (hier) nicht auf dem Schirm.
