### ISSUE TITLE
Crash bei Testscenario ausführen auf Linux

### ISSUE THREAD

**Issue by ladymagnetic** [SPoelloth/SWP16#77]
1. Crash: ungültiges Testscenario (Freitext)
2. Crash: gültiges Testscenario (mit A | (Z) | TRUE)

![crash_scenario_ausfuehren](https://cloud.githubusercontent.com/assets/18303325/16379944/5518177e-3c74-11e6-8347-026655c911aa.png)

**Comment by denis631** [comment]
Aber bei Windows funktioniert es, oder ? Ich meine das Testszenario "A | (Z) | TRUE"

**Comment by denis631** [comment]
Weißt du genauer wo der Crash auftritt. Also die Code-Linie ...

**Comment by SPoelloth** [comment]
Mehr als im Screenshot kann ich auch net sagen. Installiert euch ne VM und testets da, dauert ca 30mins.

**Comment by ladymagnetic** [comment]
Ja, bei Windows funktioniert A | (Z) | TRUE. Nur soll das Programm eben (auch) auf Linux laufen und wird auch dort getestet. Könnt ihr ja selbst auch mal mit einem gültigen und ungültigem Testscenario ausprobieren. Was bei einem ungültigem auf windows passiert, weiß ich nicht.

Edit:
So das passiert bei einem ungültigem Testscenario (Freitext) auf Windows:

![windows_ungueltiges_testscenario](https://cloud.githubusercontent.com/assets/18303325/16424955/8d860f1e-3d62-11e6-84ed-3657b9b39134.png)

Könnt ihr ja auch selbst ganz einfach ausprobieren.
