### ISSUE TITLE
Simulation und Eigene Layer => falsche Ergebnisse bei Hops / Simulation

### ISSUE THREAD

**Issue by ladymagnetic** [SPoelloth/SWP16#80]
Aufbau:
Workstation 1: SSL-Layer an zweiter Stelle eingefügt
Workstation 2: keine Veränderungen am Layerstack
Diese direkt verbunden

Simulation von
WS 1 => WS 2: Fehler aufgetreten
Hops:
Hinpaket: WS 1 kein Fehler, WS 2 Layer SSL ist am Quell- aber nicht am Zielrechner enthalten.
=> passt so

WS 2 => WS 1: Fehler aufgetreten
Hops:
Weder Hinpaket, noch Rückpaket hat Fehler.
=> In der Simulation ist ein Fehler aufgetreten, aber in den Hops kein Fehler erkennbar!!

**Comment by JPsychotic** [comment]
In der Simulation ist aber das richtige Ergebnis drinnen... das Rückpaket darf ja nicht klappen und der Fehler wird erkannt und im Result Objekt gespeichert! Auch nachdem die Simulation in der History ist, ist das Ergebnis noch richtig...

**Comment by JPsychotic** [comment]
`var results = SimulationManager.Instance.GetHopResult(true, index, hops[i].Name, hops[i + 1].Name);`

Du rufst das hier immer mit true auf... also kriegst du immer Hinpakete zurück! Nie aber Rückpakete!
