### ISSUE TITLE
Testszenario auf 2 Rechner funktioniert nicht mit Leerzeichen drin

### ISSUE THREAD

**Issue by JPsychotic** [SPoelloth/SWP16#81]
A|(B,C)|true, klappt nicht, wirft false aus.
Bei Fragen an Theresa wenden.

**Comment by Resi12** [comment]
funktioniert nicht wenn du ein Leerzeichen zwischen B,C hast

**Comment by denis631** [comment]
Bitte xml hochladen

**Comment by ladymagnetic** [comment]
Gab schon einen Commit von Denis (der wohl diesen "Bug" fixen sollte), bei mir auf Windows hat das mit dem Testscenario jetzt auf die Schnelle geklappt. Bitte nochmal testen, ob es wirklich so ist.

**Comment by ladymagnetic** [comment]
Anbei die Versuchsdateien vom Abnahmetest.
[Abnahmetest.zip](https://github.com/SPoelloth/SWP16/files/343662/Abnahmetest.zip)

**Comment by O136** [comment]
![image](https://cloud.githubusercontent.com/assets/16740762/16541927/faac0cc2-4093-11e6-8d18-fe44a9a10017.png)

Das ist Versuch3 aus der Abnahmetest.zip Datei. (Nur die Rechnernamen habe ich geändert)
Die schnelle Simulation von Rechner1 nach Rechner4 funktioniert nicht und deshalb wird sie auch so 
im Testsszenario Fenster angezeigt.

**Comment by ladymagnetic** [comment]
Was heißt in diesem Fall funktioniert nicht? Also was ist das Ergebnis der schnellen Simulation von Rechner 1 auf Rechner 4?

Es wird angezeigt, dass Simulation von Rechner 4 auf Rechner 1 fehlgeschlagen ist. Dies ist korrekt da Rechner 1 zwar Rechner 4 erreichen, aber Rechner 4 nicht Rechner 1 erreichen kann, dass Testscenario aber verlangt, dass diese Verbindung möglich ist. 
Bei Versuch 3 ist das richtige Ergebnis das Rechner 4 Rechner 1 NICHT erreichen kann.
Grund dafür ist, das Rechner 4 in einem anderen Subnetz als Rechner 1 ist und keine Route für das Subnetz von Rechner 1 hat. Dies ist so gewünscht und im Projekt umgesetzt, wenn du sonst nichts verändert hast.

Das Testscenario muss als erfolgreich sein wenn 
Rechner 4 | (Rechner 1) | FALSE

Falls das in der Testscenario-Datei anders drin stand, das war für einen Test, was genau nicht funktioniert etc.

**Comment by denis631** [comment]
Die Testszenario-Ergebnisse stimmen mit den Ergebnissen aus den schnellen Simulationen überein.

**Comment by ladymagnetic** [comment]
Fehler scheint aus meiner Sicht behoben zu sein. 
@Resi12 falls Zeit ist, bitte nochmal (unter Linux) testen -> hab nur die Testscenarios vom Abnahmetest genommen.
